config/routes.rb
WittBib::Application.routes.draw do

  devise_for :users

  resources :customers
  resources :users

  get "api/books/:isbn" => 'api/books#search'
  resources :lendings, :only => [:index] do
    member { put :cancel, :as => :return_book }
  end
  resources :books do
    resources :lendings, :except => [:index]
    collection do
      get :search
      get :query
    end
    member { put :toggle_archive }
  end
  resource :archive

  root :to => 'books#index'

  match '/exception_test' => 'exception_test#error'
end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :lendings, :dependent => :destroy

  attr_accessor :isbn
  attr_accessible :authors, :title, :isbn, :isbn_10, :isbn_13,
                  :description, :language, :page_count,
                  :published_date, :publisher, :image_url,
                  :deleted_at

  default_scope where(:deleted_at => nil)

  scope :lent, joins(:lendings).where('lendings.returned_at' => nil)
  scope :archived, where(:archived => true)

  def isbn
    @isbn || isbn_13 || isbn_10
  end

  def state
    lendings.not_available.any? ? t('not_available') : t('available')
  end

  # Generates CSV
  def self.csv(search_params = nil)
    csv = "Autoren, Titel, ISBN, Sprache, Seitenzahl, Veroeffentlichung, Verlag\n"
    Book.all.each do |e|
      csv << e.to_csv
    end
    csv
  end

  def to_csv
    require 'csv'
    CSV.generate do |csv|
      csv << [self.authors, self.title, self.isbn, self.language,
              self.page_count, self.published_date, self.publisher]
    end
  end

  def to_s
    "#{authors} - #{title}"
  end

end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  authorize_resource

  def search
    bs = BookSearch.new
    bs.search(params[:isbn])
    render :json => bs
  end

end

app/controllers/books_controller.rb
#encoding: UTF-8
class BooksController < InheritedResources::Base

  authorize_resource

  respond_to :html, :datatables

  def new
    new!
  end

  def index
    respond_to do |format|
      format.html

      format.csv do
        send_data(Book.csv,
                  :type => 'text/csv; charset=iso-8859-1; header=present',
                  :filename => "book_catalogue_#{Date.today}.csv")
      end
    end
  end

  def destroy
    destroy!(:notice => "Erfolgreich gelöscht: '#{resource}'") { books_path }
  end

  # Checks whether book is currently in archive. If so, put it back in
  # catalogue. Otherwise put book into archive.
  def toggle_archive
    book = Book.find(params[:id])
    notice = book.archived ? "Buch erfolgreich in den Katalog genommen" : 'Buch erfolgreich archiviert'
    book.toggle!(:archived)
    redirect_to books_path, :notice => notice
  end

  #def create
  #create! { :notice => t('book_created', :delete_link => 'asdf') }
  #link_to t('delete_book'), , :method => :delete) }
  #end

  # GET /books/search
  def search

    # datatables sends a search request like param1_or_param2_sw
    # '_sw' stands for 'starts with'. but since we want to have a full text
    # search, here a _contains is injected to induce a 'like' query.
    #
    # params is a frozen hash in rails. this is a workaround.
    params_search = params[:search].dup
    if params_search.keys.any? { |k| k.match(/_sw/) }

      # get the key which contains the query
      t_key = params_search.keys.reject { |k| !k.include? "_sw" }.first

      # delete _sw key and inject _contains key
      val = params_search.delete t_key
      key = t_key.gsub("_sw", "_contains")
      params_search[key] = val
    end
    params[:search] = params_search

    @books = Book.search(params[:search]).
      paginate(:page => params[:page],
               :per_page=>params[:per_page])
    respond_with @books
  end

  def query
    isbn = normalize_isbn(params[:isbn])
    length = isbn.length
    raise 'unknown isbn format' unless %w(10 13).include?(length.to_s)
    @books = Book.send("find_all_by_isbn_#{length}", isbn)
    if @books.count==1
      @book = @books.first
      render :action => 'show', :layout => false
    elsif @books.count > 1
      render :js => "window.location = '/books?isbn=#{isbn}'"
    else
      @book = Book.new(:isbn => isbn)
      render :action => 'new', :layout => false
    end
  end

  #def collection
  #  Book.includes(:lendings).collect { |b| b if !b.lendings.empty? }.compact
  #end

  private

  def normalize_isbn(isbn)
    isbn.tr_s('- ','')
  end


end

app/helpers/api/books_helper.rb
module Api::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
  # default book cover if none available
  def book_cover_picture
    if resource.image_url.blank? or resource.image_url.nil?
      image_tag "default_book_icon.jpeg"
    else
      image_tag resource.image_url
    end
  end
end

app/views/books/_form.html.haml
=semantic_form_for resource, :html => { :class => 'form-horizontal' } do |f|
  =f.inputs do
    =f.input :title, :label => "Titel"
    =f.input :authors, :label => "Autoren"
    =f.input :page_count, :label => "Seitenzahl"
    =f.input :language, :label => "Sprache"
    =f.input :description, :label => "Beschreibung"
    =f.input :published_date, :label => "Veroeffentl."
    =f.input :publisher, :label => "Verlag"
    =f.input :isbn, :as => :hidden
    =f.input :isbn_10, :label => "ISBN 10"
    =f.input :isbn_13, :label => "ISBN 13"
    =f.input :image_url, :as => :hidden
  =f.actions do
    =f.action :submit, :as => :button, :label => "Sichern"

app/views/books/archive.html.haml
.hero-unit
  .well
    %h2 Archiv
    %br

    %table.table.table-striped.table-condensed.datatable
      %thead
        %tr
          %th Autoren
          %th Titel
          %th ISBN
      %tbody
        - Book.unscoped.where('deleted_at IS NOT NULL').each do |book|
          %tr
            %td= book.authors
            %td= book.title
            %td= book.isbn

app/views/books/edit.html.haml
.hero-unit
  .well
    %h3 Buch editieren
    = render :partial => "form"

app/views/books/index.html.haml
.hero-unit
  .well
    %h2 Katalog
    %br
      .pull-right
        - if can? :manage, Book
          = link_to "Neues Buch erfassen", new_resource_path, :class => "btn primary small"
        = link_to "Exportiere Katalog", books_path(:format => :csv), :class => "btn primary small"

    %table.table.table-striped.table-condensed#books
      %thead
        %tr
          %th Autoren
          %th Titel
          %th ISBN
          %th= ""
          %th= ""
          %th= ""
          %th= ""
          %th= ""

    -# rows are filled in by datatables


    -#%td= button_to "Löschen", record, :confirm => "Sind Sie sicher?", :method => :delete

app/views/books/new.html.haml
.hero-unit
  .well
    %h3 Neues Buch anlegen
    = render :partial => "form"

app/views/books/show.html.haml
#book
  - if can? :manage, Book
    .row
      - if resource.state == t(:available)
        .span2
          = link_to(link_to "Ausleihen", new_book_lending_path(resource), :class => 'btn btn-info')
      .span2
        = link_to(link_to "Bearbeiten", edit_book_path(resource), :class => 'btn btn-warning')

  .row
    .span8
      %h2 #{resource.authors}: #{resource.title}
    .span4
      #state.pull-right.label{ :class => 'label-success' }=resource.state

  .row

    .span8
      %table#book-table
        %tr
          %td Seitenzahl
          %td #{resource.page_count}
        %tr
          %td Sprache
          %td #{resource.language}
        %tr
          %td Veroeffentlichung
          %td #{resource.published_date}
        %tr
          %td Verlag
          %td #{resource.publisher}
        %tr
          %td ISBN
          %td #{resource.isbn}
        %tr
          %td Beschreibung
          %td #{resource.description}

    .span4
      .pull-right= book_cover_picture

  - if can? :read, Lending
    .row.well
      %h3 Historie Ausleihe
      %strong Anzahl Ausleihen:
      = resource.lendings.count
      %table.table.table-striped
        %thead
          %tr
            %th Von
            %th Ausleihdatum
            %th Rueckgabedatum
        %tbody
        - resource.lendings.each do |lending|
          %tr
            - if lending.customer
              %td= link_to lending.customer.name, lending.customer
            - else
              %td Gelöschter Nutzer
            %td= lending.taken_at.to_date
            %td= lending.try(:returned_at).try(:to_date) || "Noch ausgeliehen"