config/routes.rb
WittBib::Application.routes.draw do

  devise_for :users

  resources :customers
  resources :users

  get "api/books/:isbn" => 'api/books#search'
  resources :lendings, :only => [:index] do
    member { put :cancel, :as => :return_book }
  end
  resources :books do
    resources :lendings, :except => [:index]
    collection do
      get :search
      get :query
    end
    member { put :toggle_archive }
  end
  resource :archive

  root :to => 'books#index'

  match '/exception_test' => 'exception_test#error'
end

app/models/lending.rb
class Lending < ActiveRecord::Base

  belongs_to :book
  belongs_to :customer

  attr_accessible :book_id, :customer_id

  validates :book_id, :customer_id, :taken_at,
    :presence => true

  scope :not_available, where(:returned_at => nil)

  def is_overdue?
    taken_at < 4.weeks.ago
  end

end

app/controllers/lendings_controller.rb
# encoding: UTF-8

class LendingsController < InheritedResources::Base
  authorize_resource

  def new
    if Book.find(params[:book_id]).state == t(:not_available)
      redirect_to root_path, :alert => "Bereits ausgeliehen"
    else
      super
    end
  end

  def create
    @lending = Lending.new :book_id => params[:book_id].to_i,
      :customer_id => params[:lending][:customer_id].to_i
    @lending.taken_at = DateTime.now

    if @lending.valid?
      @lending.save!
      redirect_to root_path, :notice => "Buch ausgeliehen"
    else
      redirect_to root_path, :alert => "Fehler beim Ausleihen"
    end
  end

  # return a lent book
  def cancel
    @lending = Lending.find params[:id]
    @lending.returned_at = DateTime.now
    if @lending.save
      redirect_to lendings_path, :notice => "Buch ist wieder verfügbar"
    else
      redirect_to lendings_path, :alert => "Fehler beim Zurückgeben"
    end
  end


  def collection
    @lendings ||= Lending.not_available
  end

end

app/helpers/lendings_helper.rb
module LendingsHelper
end

app/views/lendings/_form.html.haml
= semantic_form_for resource, :url => book_lendings_path,
  :html => { :class => 'form-horizontal' } do |f|
  = f.inputs do
    = f.input :customer, :label => "Kunde", :input_html => { 'data-chosen' => true }
    = f.submit "Leihe Buch aus", :class => "btn btn-primary"

app/views/lendings/index.html.haml
.hero-unit
  .well
    %h2 Verliehene Bücher
    %br
    %table.table.table-striped.table-condensed.datatable
      %thead
        %tr
          %th Buch
          %th Kunde
          %th Ausgeliehen am
          %th Innerhalb Frist
          %th
      %tbody
        - for record in collection
          %tr{:class => record.is_overdue? ? 'overdue' : 'not_overdue'}
            %td=[record.try(:book).try(:authors), record.try(:book).try(:title)].join ', '
            %td=record.try(:customer).try(:name)
            %td=record.taken_at.to_date
            %td
            %td=button_to "Zurückgeben", return_book_lending_path(record),
              :confirm => "Sind Sie sicher?", :method => :put

app/views/lendings/new.html.haml
.hero-unit
  .well
    %h3 Buch ausleihen
    = render :partial => "form"

app/views/lendings/show.html.haml
Ausgeliehenes Buch..

Noch zu definieren..