config/routes.rb
WittBib::Application.routes.draw do

  devise_for :users

  resources :customers
  resources :users

  get "api/books/:isbn" => 'api/books#search'
  resources :lendings, :only => [:index] do
    member { put :cancel, :as => :return_book }
  end
  resources :books do
    resources :lendings, :except => [:index]
    collection do
      get :search
      get :query
    end
    member { put :toggle_archive }
  end
  resource :archive

  root :to => 'books#index'

  match '/exception_test' => 'exception_test#error'
end

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title WittBib
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tag
    %meta{'charset' => 'utf-8'}/
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/

  %body
    .navbar
      .navbar-inner
        .container
          - if user_signed_in?
            %a{:class => 'btn btn-navbar', 'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
              - 3.times do
                = raw("<span class='icon-bar'></span>")
          =link_to image_tag('logo.png'), root_path

          - if user_signed_in?
            .nav-collapse.collapse
              %ul.nav
                %li
                  = link_to 'Katalog', books_path
                %li
                  = link_to 'Archiv', archive_path
                %li
                  = link_to 'Kunden', customers_path
                %li
                  = link_to 'Verliehen', lendings_path
                %li
                  = link_to 'Benutzer', users_path

                -# TODO: RIGHT!
                #user_nav.nav.pull-right
                  %li.info= "Angemeldet als #{current_user.email}"
                  %li= link_to "Abmelden", destroy_user_session_path,
                    :method => :delete
          - else
            #user_nav.nav.pull-right
              %li= link_to 'Anmelden', new_user_session_path

        - if user_signed_in?
          .container
            %ul.nav

            %ul.nav.pull-right
              %li
                #progress=image_tag 'book.gif'
              %li
                %form.form-search
                  #feedback.control-group
                    =search_field_tag :query, '', :class => 'search-query',
                      :placeholder => t('.search_placeholder'), :autocomplete => "off"
                    =submit_tag t('.search')

    #flash.container
      - if flash.count != 0
        .hero-unit
          .offset2.span8
            - flash.each do |name, msg|
              - clazz = (name == :notice) ? "success" : "error"
              .alert{ :class => "alert-#{clazz}" }
                .close{ 'data-dismiss' => "alert" }×
                = msg

    .container
      .row
        .span12#content= yield

      %footer.pull-right
        -#WittBib von
        -#!= link_to "Panter", "http://www.panter.ch", :target => :blank

    #authorization
      = user_signed_in? ? "user" : "anonymous"